### ISSUE TITLE
Any working example?

### ISSUE THREAD

**Issue by umervservices** [LasseHaslev/vue-geocoder#3]

**Comment by LasseHaslev** [comment]
Yes, but not standalone.

The geocoder component is used as the input field of the [coordinate-input component](https://github.com/LasseHaslev/vue-coordinate-input), and you can try that one out here: https://kulinaris.no/utsalgssteder.

![image](https://user-images.githubusercontent.com/3670799/37757039-e29018e8-2dab-11e8-9c07-e53f94cce163.png)
